"""screencast.compose tests.

test_view_at_* cover the composer's core policy (screencast.compose._view_at)
as pure functions -- no ffmpeg involved. test_compose_* run the real
composer against tiny synthetic clips generated by ffmpeg's own lavfi
source, skipped when ffmpeg/ffprobe aren't on PATH (this repo's CI has them
via devenv.nix's ffmpeg-headless package; a plain checkout may not)."""

from screencast.compose import _view_at
from screencast.compose import compose
from screencast.compose import ComposeError
from screencast.compose import ffprobe_duration
from screencast.timeline import Timeline
import pytest
import shutil
import subprocess


TURNS = [("author", 1.0, 3.0), ("reviewer", 5.0, 8.0)]


def test_before_any_turn_observer_is_main_with_no_inset():
    view, actor, *_ = _view_at(0.5, [], TURNS)
    assert (view, actor) == ("observer", None)


def test_inside_a_turn_the_actor_is_main_by_default():
    view, actor, *_ = _view_at(2.0, [], TURNS)
    assert (view, actor) == ("actor", "author")


def test_focus_flips_main_inside_a_turn():
    focus = [{"time": 1.5, "view": "observer", "scale": 0.4, "margin": 24, "border": 3}]
    view, actor, *_ = _view_at(2.0, focus, TURNS)
    assert (view, actor) == ("observer", "author")


def test_a_focus_event_from_an_earlier_turn_does_not_leak_into_a_later_turn():
    focus = [{"time": 1.5, "view": "observer", "scale": 0.4, "margin": 24, "border": 3}]
    view, actor, *_ = _view_at(6.0, focus, TURNS)
    assert (view, actor) == ("actor", "reviewer")


def test_gap_after_a_turn_defaults_to_observer_with_frozen_actor_inset():
    view, actor, *_ = _view_at(4.0, [], TURNS)
    assert (view, actor) == ("observer", "author")


def test_gap_focus_event_can_bring_back_the_actor():
    focus = [{"time": 3.5, "view": "actor", "scale": 0.4, "margin": 24, "border": 3}]
    view, actor, *_ = _view_at(4.0, focus, TURNS)
    assert (view, actor) == ("actor", "author")


ffmpeg_available = shutil.which("ffmpeg") and shutil.which("ffprobe")
requires_ffmpeg = pytest.mark.skipif(
    not ffmpeg_available, reason="ffmpeg/ffprobe not on PATH"
)


def make_clip(path, duration, color="blue"):
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            f"color=c={color}:s=320x180:d={duration}:r=25",
            str(path),
        ],
        check=True,
    )


@requires_ffmpeg
def test_compose_a_simple_take_produces_a_valid_output(tmp_path):
    take_dir = tmp_path / "take"
    take_dir.mkdir()
    make_clip(take_dir / "observer.webm", 6.0)
    make_clip(take_dir / "author.webm", 2.0, color="red")

    timeline = Timeline.new("observer.webm")
    timeline.add_actor_clip("author", "author.webm", offset=1.0, duration=2.0)
    timeline.add_event({"type": "turn_start", "time": 1.0, "actor": "author"})
    timeline.add_event({"type": "turn_end", "time": 3.0, "actor": "author"})
    timeline.save(take_dir / "timeline.json")

    output = compose(take_dir)
    assert output.exists()
    assert ffprobe_duration(output) == pytest.approx(6.0, abs=0.5)


@requires_ffmpeg
def test_compose_with_chapter_and_hold_extends_output_duration(tmp_path):
    take_dir = tmp_path / "take"
    take_dir.mkdir()
    make_clip(take_dir / "observer.webm", 3.0)
    make_clip(take_dir / "author.webm", 1.0, color="red")

    timeline = Timeline.new("observer.webm")
    timeline.add_actor_clip("author", "author.webm", offset=0.5, duration=1.0)
    timeline.add_event({"type": "turn_start", "time": 0.5, "actor": "author"})
    timeline.add_event(
        {
            "type": "chapter",
            "time": 0.5,
            "eyebrow": "Story",
            "title": "Author",
            "subtitle": "Doing a thing",
            "duration": 2.0,
        }
    )
    timeline.add_event({"type": "turn_end", "time": 1.5, "actor": "author"})
    timeline.add_event({"type": "hold", "time": 3.0, "duration": 1.5})
    timeline.save(take_dir / "timeline.json")

    output = compose(take_dir)
    # 3.0s of real footage + 2.0s inserted title card + 1.5s inserted hold.
    assert ffprobe_duration(output) == pytest.approx(6.5, abs=0.5)


@requires_ffmpeg
def test_compose_is_reproducible_from_the_same_timeline(tmp_path):
    """A human re-cutting a take by editing focus/hold events and
    re-running the composer needs no re-recording -- exercised here by
    composing the same timeline twice and getting the same duration."""
    take_dir = tmp_path / "take"
    take_dir.mkdir()
    make_clip(take_dir / "observer.webm", 4.0)
    timeline = Timeline.new("observer.webm")
    timeline.save(take_dir / "timeline.json")

    first = compose(take_dir, output=take_dir / "first.webm")
    second = compose(take_dir, output=take_dir / "second.webm")
    assert ffprobe_duration(first) == pytest.approx(ffprobe_duration(second), abs=0.1)


@requires_ffmpeg
def test_compose_rejects_overlapping_turns(tmp_path):
    take_dir = tmp_path / "take"
    take_dir.mkdir()
    make_clip(take_dir / "observer.webm", 6.0)
    make_clip(take_dir / "a.webm", 3.0, color="red")
    make_clip(take_dir / "b.webm", 3.0, color="green")

    timeline = Timeline.new("observer.webm")
    timeline.add_actor_clip("a", "a.webm", offset=0.0, duration=3.0)
    timeline.add_actor_clip("b", "b.webm", offset=1.0, duration=3.0)
    timeline.add_event({"type": "turn_start", "time": 0.0, "actor": "a"})
    timeline.add_event({"type": "turn_end", "time": 3.0, "actor": "a"})
    timeline.add_event({"type": "turn_start", "time": 1.0, "actor": "b"})
    timeline.add_event({"type": "turn_end", "time": 4.0, "actor": "b"})
    timeline.save(take_dir / "timeline.json")

    with pytest.raises(ComposeError):
        compose(take_dir)


@requires_ffmpeg
def test_compose_refuses_unknown_timeline_version(tmp_path):
    take_dir = tmp_path / "take"
    take_dir.mkdir()
    make_clip(take_dir / "observer.webm", 2.0)
    timeline = Timeline.new("observer.webm")
    timeline.save(take_dir / "timeline.json")
    import json

    data = json.loads((take_dir / "timeline.json").read_text())
    data["version"] = 1
    (take_dir / "timeline.json").write_text(json.dumps(data))

    with pytest.raises(Exception):  # noqa: B017 -- TimelineError from Timeline.load
        compose(take_dir)
